apiVersion: skaffold/v1beta1
kind: Config
## Default profile for use with `skaffold dev`
build:
  artifacts:
  - image: podinfo
    docker:
      dockerfile: ./Dockerfile.build
deploy:
  kubectl:
    manifests:
    - deploy/skaffold/dev/*
profiles:
- name: test
  ## This profile runs unit tests and builds the image
  build:
    artifacts:
    - image: stefanprodan/podinfo
      docker:
        dockerfile: ./Dockerfile.build
    local:
      push: false
- name: production
  ## This profile pushes the image
  build:
    artifacts:
    - image: stefanprodan/podinfo
      docker:
        dockerfile: ./Dockerfile.build
    local:
      push: true